from django.urls import path

from myapp.views import *

app_name = 'NB'

urlpatterns = [
    path('company_home/', company_home, name='company_home'),
    path('company_register_home/', company_register_home, name='company_register_home'),
    path('company_register/', company_register, name='company_register'),
    path('company_login/', company_login, name='company_login'),
    path('go_company_reset/', go_company_reset, name='go_company_reset'),
    path('go_company_mine/', go_company_mine, name='go_company_mine'),
    path('go_company_vip/', go_company_vip, name='go_company_vip'),
    path('go_company_zhiweisousuo/<pagenum>/', go_company_zhiweisousuo, name='go_company_zhiweisousuo'),
    path('go_company_shoujianxiang/<pagenum>/', go_cpmpany_shoujianxiang, name='go_cpmpany_shoujianxiang'),
    path('go_company_rencaijia/<pagenum>/', go_company_recaija, name='go_company_recaijia'),
    path('company_set/', email_phone_set, name='company_set'),
    path('company_reset/', email_phone_reset, name='company_reset'),
    path('set_phone/', set_phone, name='set_phone'),
    path('set_email/', set_email, name='set_email'),
    path('change_company/',change_company,name='change_company'),
    path('check_resume/<id>/',check_resume,name='check_resume'),
    path('download_resume/',download_resume,name='download_resume'),
    path('jiaru_resume/',jiaru_resume,name='jiaru_resume'),
    path('job_save/', job_release, name='job_save'),
    path('goumai_vip/',goumai_vip,name='goumai_vip'),
    path('xia_xian/<id>/',xia_xian,name='xia_xian'),
    path('re_resume/<id>/',re_resume,name='re_resume'),
    path('upload_job_home/',upload_job_home,name='upload_job_home'),
    path('company_user_name/', company_user_name, name='company_user_name'),
    path('company_name/', company_name, name='company_name'),
    path('search_company_job/<pagenum>/', search_company_job, name='search_company_job'),

    path('user_home/', user_home, name='user_home'),
    path('user_register_home/', user_register_home, name='user_register_home'),
    path('user_register/', user_register, name='user_register'),
    path('user_login/', user_login, name='user_login'),
    path('go_user_reset/', go_user_reset, name='go_user_reset'),
    path('go_user_mine/', go_user_mine, name='go_user_mine'),
    path('zwss_home/<pagenum>/', zwss_home, name='zwss_home'),
    path('user_set/', email_phone_set, name='user_set'),
    path('user_reset/', email_phone_reset, name='user_reset'),
    path('go_user_vip/', go_user_vip, name='go_user_vip'),
    path('user_zwsc/<pagenum>/', go_user_zwsc, name='user_zwsc'),
    path('user_tdjd/<pagenum>/', go_user_tdjd, name='user_tdjd'),
    path('user_pbgs/<pagenum>/', go_user_pbgs, name='user_pbgs'),
    path('user_skgw/<pagenum>/', go_user_skgw, name='user_skgw'),
    path('resume_show/', go_user_jlll, name='resume_show'),
    path('resume_upload/', go_resume_upload, name='resume_upload'),
    path('img/', img, name='img'),
    path('save_xinxi/', save_xinxi, name='save_xinxi'),
    path('change_xinxi/', change_xinxi, name='change_xinxi'),
    path('find_resume/', find_resume, name='find_resume'),
    path('resume_refresh/', resume_refresh, name='resume_refresh'),
    path('cancel_pingbi/<name>/', cancel_pingbi, name='cancel_pingbi'),
    path('zhiweishoucang_toudi/', zhiweishoucang_toudi, name='zhiweishoucang_toudi'),
    path('zhiweishoucang_shanchu/<id>/', zhiweishoucang_shanchu, name='zhiweishoucang_shanchu'),
    path('zhiwei_show/<id>/', zhiwei_show, name='zhiwei_show'),
    path('pingbi_company/', pingbi_company, name='pingbi_company'),
    path('company_show/<id>/', company_show, name='company_show'),
    path('collect_zhiwei/', collect_zhiwei, name='collect_zhiwei'),

    path('quit_login/', quit_login, name='quit_login'),
]
